version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mes123
      POSTGRES_USER: messalas
      POSTGRES_DB: booksdb